Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -48,8 +48,8 @@ steps:
       echo "CRITICAL=$CRITICAL"
       HIGH=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/6324/summary' | jq -r '.issueCountHigh')
       echo "HIGH=$HIGH"
-      if[$CRITICAL -gt 10]
-      then
-      echo "failing task because number of critical issues are greater than 10"
-      exit 1
+      if [[$CRITICAL -gt 10]]
+        then
+          echo "failing task because number of critical issues are greater than 10"
+          exit 1
       fi
