Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -48,48 +48,53 @@ steps:
 #       echo $date
 #       scan_id=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans?startedOnStartDate=2022-08-04' | jq -r '.scanId')
 #       echo $scan_id
-      
-      
-# - task: Bash@3
-#   inputs:
-#     targetType: 'inline'
-#     script: |
-#       SCANID=6339
-#       URL="https://api.sandbox.fortify.com/api/v3/scans/${SCANID}/summary"
-#       CURL="-X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) '${URL}'"
-#       echo $CURL
-#       CRITICAL=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/6339/summary' | jq -r '.issueCountCritical')
-#       HIGH=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/6324/summary' | jq -r '.issueCountHigh')
-#       SUM=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/6324/summary' | jq -r '.totalIssues')
-#       echo "Total Sum of all vulnerabilities = $SUM"
-#       echo "CRITICAL = $CRITICAL"
-#       echo "HIGH = $HIGH"
-#       if [ $CRITICAL -gt 5 ]
-#       then
-#         echo "Failing task because number of critical issues are greater than 5"
-#         exit 1
-#       elif [ $HIGH -gt 10 ]
-#       then
-#         echo "Failing task because number of high issues are greater than 10"
-#         exit 1
-#       elif [ $SUM -gt 50 ]
-#       then
-#         echo "Failing task because number of total issues are greater than 50"
-#         exit 1
-#       else
-#         echo "PASSED"
-#       fi
-
 - task: Bash@3
   inputs:
     targetType: 'inline'
     script: |
       auth=$(curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Connection: close' -d 'grant_type=client_credentials&scope=api-tenant&client_id=$(FOD-API-KEY)&client_secret=$(FOD-SECRET)' 'https://api.sandbox.fortify.com/oauth/token')
-                   tok3n=$( echo "$auth" | jq '.["access_token"]' )
-                   tok3n="${tok3n:1:-1}"
-                   scan_details=$(curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} 'https://api.sandbox.fortify.com/api/v3/releases/9516/dynamic-scans/scan-setup')
-                   assessmenttypeID=$( echo "$scan_details" | jq '.assessmentTypeId')
-                   entitlementID=$( echo "$scan_details" | jq '.entitlementId')
-                   echo $assessmenttypeID
-                   echo $entitlementID
-                   curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} -d '{"startDate": "2022-08-29T11:52:08.980Z", "assessmentTypeId": ${assessmenttypeID}, "entitlementId": ${entitlementID}, "entitlementFrequencyType": "SingleScan", "isRemediationScan": false, "isBundledAssessment": false, "parentAssessmentTypeId": 0, "applyPreviousScanSettings": false, "scanMethodType": "IDE", "scanTool": "string", "scanToolVersion": "string"}' 'https://api.sandbox.fortify.com/api/v3/releases/9516/dynamic-scans/start-scan'
+                    tok3n=$( echo "$auth" | jq '.["access_token"]' )
+                    tok3n="${tok3n:1:-1}"
+                    releaseid=9516
+                    scan_details=$(curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} 'https://api.sandbox.fortify.com/api/v3/releases/'${releaseid}'/dynamic-scans/scan-setup')
+                    assessmenttypeID=$( echo "$scan_details" | jq '.assessmentTypeId')
+                    entitlementID=$( echo "$scan_details" | jq '.entitlementId')
+                    echo $assessmenttypeID
+                    echo $entitlementID
+                    scanid=6339
+             CRITICAL=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/'${scanid}'/summary' | jq -r '.issueCountCritical')
+             HIGH=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/6324/summary' | jq -r '.issueCountHigh')
+             SUM=$(curl -X GET --header 'Accept: application/json' --header $(BEARER_TOKEN) 'https://api.sandbox.fortify.com/api/v3/scans/6324/summary' | jq -r '.totalIssues')
+             echo "Total Sum of all vulnerabilities = $SUM"
+             echo "CRITICAL = $CRITICAL"
+             echo "HIGH = $HIGH"
+             if [ $CRITICAL -gt 5 ]
+             then
+               echo "Failing task because number of critical issues are greater than 5"
+               exit 1
+             elif [ $HIGH -gt 10 ]
+             then
+               echo "Failing task because number of high issues are greater than 10"
+               exit 1
+             elif [ $SUM -gt 50 ]
+             then
+               echo "Failing task because number of total issues are greater than 50"
+               exit 1
+             else
+               echo "PASSED"
+             fi
+       
+
+# - task: Bash@3
+#   inputs:
+#     targetType: 'inline'
+#     script: |
+#       auth=$(curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Connection: close' -d 'grant_type=client_credentials&scope=api-tenant&client_id=$(FOD-API-KEY)&client_secret=$(FOD-SECRET)' 'https://api.sandbox.fortify.com/oauth/token')
+#                    tok3n=$( echo "$auth" | jq '.["access_token"]' )
+#                    tok3n="${tok3n:1:-1}"
+#                    scan_details=$(curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} 'https://api.sandbox.fortify.com/api/v3/releases/9516/dynamic-scans/scan-setup')
+#                    assessmenttypeID=$( echo "$scan_details" | jq '.assessmentTypeId')
+#                    entitlementID=$( echo "$scan_details" | jq '.entitlementId')
+#                    echo $assessmenttypeID
+#                    echo $entitlementID
+#                    curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer '${tok3n} -d '{"startDate": "2022-08-29T11:52:08.980Z", "assessmentTypeId": ${assessmenttypeID}, "entitlementId": ${entitlementID}, "entitlementFrequencyType": "SingleScan", "isRemediationScan": false, "isBundledAssessment": false, "parentAssessmentTypeId": 0, "applyPreviousScanSettings": false, "scanMethodType": "IDE", "scanTool": "string", "scanToolVersion": "string"}' 'https://api.sandbox.fortify.com/api/v3/releases/9516/dynamic-scans/start-scan'
