Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -56,6 +56,14 @@ steps:
       then
         echo "Failing task because number of critical issues are greater than 5"
         exit 1
+      elif [ $HIGH -gt 10 ]
+      then
+        echo "Failing task because number of high issues are greater than 10"
+        exit 1
+      elif [ $SUM -gt 50 ]
+      then
+        echo "Failing task because number of total issues are greater than 50"
+        exit 1
       else
         echo "PASSED"
       fi
